---
- hosts: web
  become: true
  vars:
    webServer: "apache2"
  tasks:
    - name: Install apache
      apt:
        name: "{{ webServer }}"
        state: latest
        update_cache: yes

    - name: Enable service apache2
      service:
        name: apache2
        enabled: yes
    
    - name: Copy HTML files
      copy:
        src: /home/adminuser/playbooks/htmlFiles/
        dest: /var/www/html/
        owner: 'www-data'
      notify: restart apache2
    
  handlers:
    - name: restart apache2
      service:
        name: apache2
        state: restarted
        

- hosts: db  
  vars:
    dbServer: "mariadb-server"
  become: true
  tasks:
    - name: Install MariabDB
      apt:
        name: "{{ dbServer }}"
        state: latest
        update_cache: yes

